# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

from importlib import metadata

# -- Project information -----------------------------------------------------
project = 'DRPF'
project_copyright = '2026, Panagiotis Papakonstantinou'
author = 'Panagiotis Papakonstantinou'

# Dynamically fetch the version from the installed package
try:
    # This reads the version directly from the metadata generated by setup.py
    release = metadata.version('drpf') 
    version = '.'.join(release.split('.')[:2])
except metadata.PackageNotFoundError:
    release = '0.9.0'
    version = '0.9'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx_autodoc_typehints',
    'sphinx.ext.viewcode',
    'sphinx.ext.mathjax',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
master_doc = 'index'
language = 'en'

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']